// src/Offices/officeData.js
import { Wrench, Leaf, ShieldCheck, TrafficCone, HeartPulse, Landmark, Wallet, Accessibility, HeartHandshake, Briefcase, Users, FileText } from "lucide-react";

const engineeringOffice = {
  slug: "engineering",
  code: "DEPT-001",
  name: "City Engineering Office",
  shortName: "Engineering",
  holder: "Engr. Juan Dela Cruz",
  email: "engineering@malaybalay.gov.ph",
  role: "Office Admin",
  icon: Wrench,
  stats: [
    { title: "Assigned to Office", value: "48", note: "+6 this week" },
    { title: "In Progress", value: "31", note: "+9 vs last week" },
    { title: "Resolved", value: "124", note: "+14 vs last week" },
    { title: "Critical", value: "8", note: "2 since yesterday" },
    { title: "Avg. Response", value: "2.4 hrs", note: "-0.3 hrs from last week" },
  ],
  categories: ["Road / Infrastructure", "Streetlights / Electrical", "Drainage", "Bridges & Structures"],
  categoryBreakdown: [
    { name: "Road / Infrastructure", percent: "52% (211)", color: "bg-red-700" },
    { name: "Streetlights / Electrical", percent: "24% (97)", color: "bg-red-600" },
    { name: "Drainage", percent: "16% (65)", color: "bg-red-500" },
    { name: "Bridges & Structures", percent: "8% (32)", color: "bg-red-400" },
  ],
  problemAreas: [
    { area: "Casisang", reports: "156 reports" },
    { area: "Kalasungay", reports: "132 reports" },
    { area: "Sumpong", reports: "98 reports" },
    { area: "Bangcud", reports: "87 reports" },
    { area: "Aglayan", reports: "76 reports" },
  ],
  priorityBreakdown: [
    { name: "Critical", count: 8, color: "bg-red-700", width: 17 },
    { name: "High", count: 22, color: "bg-red-500", width: 46 },
    { name: "Medium", count: 12, color: "bg-amber-500", width: 25 },
    { name: "Low", count: 6, color: "bg-gray-400", width: 13 },
  ],
  recentReports: [
    {
      id: "#MBY-2025-1245",
      issue: "Large pothole along National Highway",
      description: "Large pothole causing vehicles to slow down and creating a safety risk for motorists.",
      location: "Sayre Highway, Casisang",
      barangay: "Casisang",
      category: "Road / Infrastructure",
      status: "In Progress",
      priority: "High",
      reported: "June 8, 2025 9:41 AM",
      image: "https://picsum.photos/seed/acors-eng-1245/300/200",
    },
    {
      id: "#MBY-2025-1243",
      issue: "Broken streetlight in front of school",
      description: "Streetlight not working near Kalasungay Central School, dark at night.",
      location: "Kalasungay Central School",
      barangay: "Kalasungay",
      category: "Streetlights / Electrical",
      status: "Assigned",
      priority: "Low",
      reported: "June 8, 2025 7:02 AM",
      image: "https://picsum.photos/seed/acors-eng-1243/300/200",
    },
    {
      id: "#MBY-2025-1239",
      issue: "Cracked railing on Managok bridge",
      description: "Concrete railing cracked and leaning, needs structural assessment.",
      location: "Managok Bridge",
      barangay: "Bangcud",
      category: "Bridges & Structures",
      status: "Resolved",
      priority: "Medium",
      reported: "June 7, 2025 3:20 PM",
      resolved: "June 9, 2025 10:42 AM",
      image: "https://picsum.photos/seed/acors-eng-1239/300/200",
    },
    {
      id: "#MBY-2025-1231",
      issue: "Clogged drainage along Sayre Highway",
      description: "Drainage canal clogged with debris causing water to pool on the road.",
      location: "Sayre Highway, Sumpong",
      barangay: "Sumpong",
      category: "Drainage",
      status: "Resolved",
      priority: "Medium",
      reported: "June 6, 2025 2:05 PM",
      resolved: "June 9, 2025 8:15 AM",
      image: "https://picsum.photos/seed/acors-eng-1231/300/200",
    },
    {
      id: "#MBY-2025-1227",
      issue: "Sinkhole near public market",
      description: "Sinkhole forming near the public market entrance, barricaded for now.",
      location: "Public Market, Casisang",
      barangay: "Casisang",
      category: "Road / Infrastructure",
      status: "In Progress",
      priority: "Critical",
      reported: "June 6, 2025 10:48 AM",
      image: "https://picsum.photos/seed/acors-eng-1227/300/200",
    },
  ],
  incidents: [
    {
      id: "#MBY-2025-1245",
      title: "Large pothole along National Highway",
      category: "Road / Infrastructure",
      barangay: "Casisang",
      status: "In Progress",
      priority: "High",
      count: 15,
      top: "46%",
      left: "56%",
    },
    {
      id: "#MBY-2025-1227",
      title: "Sinkhole near public market",
      category: "Road / Infrastructure",
      barangay: "Casisang",
      status: "In Progress",
      priority: "Critical",
      count: 12,
      top: "63%",
      left: "47%",
    },
    {
      id: "#MBY-2025-1243",
      title: "Broken streetlight in front of school",
      category: "Streetlights / Electrical",
      barangay: "Kalasungay",
      status: "Assigned",
      priority: "Low",
      count: 8,
      top: "23%",
      left: "51%",
    },
    {
      id: "#MBY-2025-1239",
      title: "Cracked railing on Managok bridge",
      category: "Bridges & Structures",
      barangay: "Bangcud",
      status: "Under Review",
      priority: "Medium",
      count: 5,
      top: "70%",
      left: "34%",
    },
    {
      id: "#MBY-2025-1231",
      title: "Clogged drainage along Sayre Highway",
      category: "Drainage",
      barangay: "Sumpong",
      status: "Pending",
      priority: "Medium",
      count: 6,
      top: "34%",
      left: "78%",
    },
  ],
};

const cenroOffice = {
  slug: "cenro",
  code: "DEPT-002",
  name: "City Environment and Natural Resources Office",
  shortName: "CENRO",
  holder: "Maria Santos",
  email: "cenro@malaybalay.gov.ph",
  role: "Office Admin",
  icon: Leaf,
  stats: [
    { title: "Assigned to Office", value: "36", note: "+4 this week" },
    { title: "In Progress", value: "22", note: "+6 vs last week" },
    { title: "Resolved", value: "98", note: "+11 vs last week" },
    { title: "Critical", value: "3", note: "1 since yesterday" },
    { title: "Avg. Response", value: "3.1 hrs", note: "-0.2 hrs from last week" },
  ],
  categories: ["Garbage / Waste", "Illegal Dumping", "Sanitation", "Tree Management"],
  categoryBreakdown: [
    { name: "Garbage / Waste", percent: "55% (164)", color: "bg-red-700" },
    { name: "Illegal Dumping", percent: "18% (54)", color: "bg-red-600" },
    { name: "Sanitation", percent: "15% (45)", color: "bg-red-500" },
    { name: "Tree Management", percent: "12% (36)", color: "bg-red-400" },
  ],
  problemAreas: [
    { area: "Sumpong", reports: "121 reports" },
    { area: "Casisang", reports: "104 reports" },
    { area: "Aglayan", reports: "88 reports" },
    { area: "Kalasungay", reports: "72 reports" },
    { area: "Bangcud", reports: "58 reports" },
  ],
  priorityBreakdown: [
    { name: "Critical", count: 3, color: "bg-red-700", width: 8 },
    { name: "High", count: 14, color: "bg-red-500", width: 39 },
    { name: "Medium", count: 12, color: "bg-amber-500", width: 33 },
    { name: "Low", count: 7, color: "bg-gray-400", width: 19 },
  ],
  recentReports: [
    {
      id: "#MBY-2025-1244",
      issue: "Garbage accumulation near the river",
      description: "Garbage pile reported near the riverbank area in Sumpong.",
      location: "Sawaga River, Sumpong",
      barangay: "Sumpong",
      category: "Garbage / Waste",
      status: "Under Review",
      priority: "Medium",
      reported: "June 8, 2025 8:15 AM",
      image: "https://picsum.photos/seed/acors-cen-1244/300/200",
    },
    {
      id: "#MBY-2025-1240",
      issue: "Illegal dumping near vacant lot",
      description: "Construction debris illegally dumped in a vacant lot at night.",
      location: "Purok 2, Bangcud",
      barangay: "Bangcud",
      category: "Illegal Dumping",
      status: "Resolved",
      priority: "Medium",
      reported: "June 7, 2025 6:55 PM",
      resolved: "June 9, 2025 9:30 AM",
      image: "https://picsum.photos/seed/acors-cen-1240/300/200",
    },
    {
      id: "#MBY-2025-1236",
      issue: "Uncollected garbage in Purok 4",
      description: "Garbage bags left uncollected for three days, attracting stray animals.",
      location: "Purok 4, Casisang",
      barangay: "Casisang",
      category: "Garbage / Waste",
      status: "In Progress",
      priority: "High",
      reported: "June 7, 2025 1:30 PM",
      image: "https://picsum.photos/seed/acors-cen-1236/300/200",
    },
    {
      id: "#MBY-2025-1232",
      issue: "Fallen tree blocking community road",
      description: "Large tree fell after a storm, blocking access to the community.",
      location: "Kalasungay East",
      barangay: "Kalasungay",
      category: "Tree Management",
      status: "Resolved",
      priority: "High",
      reported: "June 6, 2025 4:12 PM",
      resolved: "June 8, 2025 5:20 PM",
      image: "https://picsum.photos/seed/acors-cen-1232/300/200",
    },
    {
      id: "#MBY-2025-1228",
      issue: "Open dumpsite complaint",
      description: "Residents reporting a small open dumpsite near the creek.",
      location: "Purok 5, Aglayan",
      barangay: "Aglayan",
      category: "Sanitation",
      status: "In Progress",
      priority: "Critical",
      reported: "June 6, 2025 9:20 AM",
      image: "https://picsum.photos/seed/acors-cen-1228/300/200",
    },
  ],
  incidents: [
    {
      id: "#MBY-2025-1244",
      title: "Garbage accumulation near the river",
      category: "Garbage / Waste",
      barangay: "Sumpong",
      status: "Under Review",
      priority: "Medium",
      count: 6,
      top: "34%",
      left: "78%",
    },
    {
      id: "#MBY-2025-1236",
      title: "Uncollected garbage in Purok 4",
      category: "Garbage / Waste",
      barangay: "Casisang",
      status: "In Progress",
      priority: "High",
      count: 10,
      top: "58%",
      left: "50%",
    },
    {
      id: "#MBY-2025-1240",
      title: "Illegal dumping near vacant lot",
      category: "Illegal Dumping",
      barangay: "Bangcud",
      status: "Pending",
      priority: "Medium",
      count: 5,
      top: "70%",
      left: "34%",
    },
    {
      id: "#MBY-2025-1232",
      title: "Fallen tree blocking community road",
      category: "Tree Management",
      barangay: "Kalasungay",
      status: "Assigned",
      priority: "High",
      count: 7,
      top: "20%",
      left: "62%",
    },
    {
      id: "#MBY-2025-1228",
      title: "Open dumpsite complaint",
      category: "Sanitation",
      barangay: "Aglayan",
      status: "In Progress",
      priority: "Critical",
      count: 12,
      top: "66%",
      left: "72%",
    },
  ],
};

const cdrrmoOffice = {
  slug: "cdrrmo",
  code: "DEPT-003",
  name: "City Disaster Risk Reduction and Management Office",
  shortName: "CDRRMO",
  holder: "Pedro Reyes",
  email: "cdrrmo@malaybalay.gov.ph",
  role: "Office Admin",
  icon: ShieldCheck,
  stats: [
    { title: "Assigned to Office", value: "24", note: "+3 this week" },
    { title: "In Progress", value: "14", note: "+5 vs last week" },
    { title: "Resolved", value: "87", note: "+9 vs last week" },
    { title: "Critical", value: "11", note: "4 since yesterday" },
    { title: "Avg. Response", value: "1.8 hrs", note: "-0.4 hrs from last week" },
  ],
  categories: ["Flooding / Drainage", "Fallen Trees", "Emergencies", "Hazards"],
  categoryBreakdown: [
    { name: "Flooding / Drainage", percent: "42% (96)", color: "bg-red-700" },
    { name: "Emergencies", percent: "24% (55)", color: "bg-red-600" },
    { name: "Fallen Trees", percent: "21% (48)", color: "bg-red-500" },
    { name: "Hazards", percent: "13% (30)", color: "bg-red-400" },
  ],
  problemAreas: [
    { area: "Aglayan", reports: "94 reports" },
    { area: "Bangcud", reports: "81 reports" },
    { area: "Sumpong", reports: "73 reports" },
    { area: "Casisang", reports: "66 reports" },
    { area: "Kalasungay", reports: "52 reports" },
  ],
  priorityBreakdown: [
    { name: "Critical", count: 11, color: "bg-red-700", width: 46 },
    { name: "High", count: 7, color: "bg-red-500", width: 29 },
    { name: "Medium", count: 4, color: "bg-amber-500", width: 17 },
    { name: "Low", count: 2, color: "bg-gray-400", width: 8 },
  ],
  recentReports: [
    {
      id: "#MBY-2025-1242",
      issue: "Flooding during heavy rain",
      description: "Flooding in Purok 3 during heavy rainfall, water reaching knee level.",
      location: "Purok 3, Aglayan",
      barangay: "Aglayan",
      category: "Flooding / Drainage",
      status: "In Progress",
      priority: "Critical",
      reported: "June 7, 2025 6:40 PM",
      image: "https://picsum.photos/seed/acors-cdr-1242/300/200",
    },
    {
      id: "#MBY-2025-1238",
      issue: "Landslide risk along hillside",
      description: "Soil movement observed on the hillside after continuous rain.",
      location: "Hillside, Bangcud",
      barangay: "Bangcud",
      category: "Hazards",
      status: "Assigned",
      priority: "High",
      reported: "June 7, 2025 11:25 AM",
      image: "https://picsum.photos/seed/acors-cdr-1238/300/200",
    },
    {
      id: "#MBY-2025-1234",
      issue: "Fallen tree on power line",
      description: "Tree fell on a power line, sparking and blocking the road.",
      location: "Kalasungay North",
      barangay: "Kalasungay",
      category: "Fallen Trees",
      status: "Resolved",
      priority: "High",
      reported: "June 7, 2025 8:50 AM",
      resolved: "June 9, 2025 11:05 AM",
      image: "https://picsum.photos/seed/acors-cdr-1234/300/200",
    },
    {
      id: "#MBY-2025-1230",
      issue: "Evacuation pre-positioning request",
      description: "Barangay requesting pre-positioned rescue assets ahead of the weather advisory.",
      location: "Barangay Hall, Sumpong",
      barangay: "Sumpong",
      category: "Emergencies",
      status: "Resolved",
      priority: "Medium",
      reported: "June 6, 2025 3:15 PM",
      resolved: "June 8, 2025 4:40 PM",
      image: "https://picsum.photos/seed/acors-cdr-1230/300/200",
    },
    {
      id: "#MBY-2025-1226",
      issue: "Structure fire assistance",
      description: "Requesting CDRRMO support for fire response at a residential structure.",
      location: "Purok 1, Casisang",
      barangay: "Casisang",
      category: "Emergencies",
      status: "In Progress",
      priority: "Critical",
      reported: "June 6, 2025 8:05 AM",
      image: "https://picsum.photos/seed/acors-cdr-1226/300/200",
    },
  ],
  incidents: [
    {
      id: "#MBY-2025-1242",
      title: "Flooding during heavy rain",
      category: "Flooding / Drainage",
      barangay: "Aglayan",
      status: "In Progress",
      priority: "Critical",
      count: 12,
      top: "66%",
      left: "72%",
    },
    {
      id: "#MBY-2025-1238",
      title: "Landslide risk along hillside",
      category: "Hazards",
      barangay: "Bangcud",
      status: "Assigned",
      priority: "High",
      count: 8,
      top: "70%",
      left: "34%",
    },
    {
      id: "#MBY-2025-1234",
      title: "Fallen tree on power line",
      category: "Fallen Trees",
      barangay: "Kalasungay",
      status: "Under Review",
      priority: "High",
      count: 6,
      top: "22%",
      left: "58%",
    },
    {
      id: "#MBY-2025-1230",
      title: "Evacuation pre-positioning request",
      category: "Emergencies",
      barangay: "Sumpong",
      status: "Pending",
      priority: "Medium",
      count: 4,
      top: "34%",
      left: "78%",
    },
    {
      id: "#MBY-2025-1226",
      title: "Structure fire assistance",
      category: "Emergencies",
      barangay: "Casisang",
      status: "In Progress",
      priority: "Critical",
      count: 15,
      top: "46%",
      left: "56%",
    },
  ],
};

const trafficOffice = {
  slug: "traffic",
  code: "DEPT-007",
  name: "Traffic Management Center",
  shortName: "Traffic",
  holder: "Mark Villanueva",
  email: "traffic@malaybalay.gov.ph",
  role: "Responder",
  icon: TrafficCone,
  stats: [
    { title: "Assigned to Office", value: "21", note: "+5 this week" },
    { title: "In Progress", value: "12", note: "+4 vs last week" },
    { title: "Resolved", value: "61", note: "+8 vs last week" },
    { title: "Critical", value: "6", note: "2 since yesterday" },
    { title: "Avg. Response", value: "2.6 hrs", note: "-0.2 hrs from last week" },
  ],
  categories: ["Traffic Congestion", "Road Obstruction", "Stalled Vehicles", "Parking Violations"],
  categoryBreakdown: [
    { name: "Traffic Congestion", percent: "40% (72)", color: "bg-red-700" },
    { name: "Road Obstruction", percent: "25% (45)", color: "bg-red-600" },
    { name: "Stalled Vehicles", percent: "22% (40)", color: "bg-red-500" },
    { name: "Parking Violations", percent: "13% (23)", color: "bg-red-400" },
  ],
  problemAreas: [
    { area: "Casisang", reports: "118 reports" },
    { area: "Sumpong", reports: "96 reports" },
    { area: "Kalasungay", reports: "84 reports" },
    { area: "Bangcud", reports: "61 reports" },
    { area: "Aglayan", reports: "49 reports" },
  ],
  priorityBreakdown: [
    { name: "Critical", count: 6, color: "bg-red-700", width: 29 },
    { name: "High", count: 9, color: "bg-red-500", width: 43 },
    { name: "Medium", count: 4, color: "bg-amber-500", width: 19 },
    { name: "Low", count: 2, color: "bg-gray-400", width: 10 },
  ],
  recentReports: [
    {
      id: "#MBY-2025-1241",
      issue: "Stalled truck blocking Sayre lane",
      description: "Stalled delivery truck occupying one lane of Sayre Highway.",
      location: "Sayre Highway, Casisang",
      barangay: "Casisang",
      category: "Stalled Vehicles",
      status: "In Progress",
      priority: "High",
      reported: "June 7, 2025 4:30 PM",
      image: "https://picsum.photos/seed/acors-tr-1241/300/200",
    },
    {
      id: "#MBY-2025-1237",
      issue: "Heavy congestion near public market",
      description: "Bumper-to-bumper traffic near the public market during peak hours.",
      location: "Public Market, Casisang",
      barangay: "Casisang",
      category: "Traffic Congestion",
      status: "Assigned",
      priority: "Medium",
      reported: "June 7, 2025 10:10 AM",
      image: "https://picsum.photos/seed/acors-tr-1237/300/200",
    },
    {
      id: "#MBY-2025-1233",
      issue: "Road obstruction from fallen tree",
      description: "Fallen tree partially blocking a lane; traffic control requested.",
      location: "Kalasungay East",
      barangay: "Kalasungay",
      category: "Road Obstruction",
      status: "Resolved",
      priority: "High",
      reported: "June 7, 2025 7:40 AM",
      resolved: "June 9, 2025 9:12 AM",
      image: "https://picsum.photos/seed/acors-tr-1233/300/200",
    },
    {
      id: "#MBY-2025-1229",
      issue: "Parking violations along Rizal Avenue",
      description: "Double parking along Rizal Avenue causing congestion for commuters.",
      location: "Rizal Avenue, Sumpong",
      barangay: "Sumpong",
      category: "Parking Violations",
      status: "Resolved",
      priority: "Low",
      reported: "June 6, 2025 5:55 PM",
      resolved: "June 8, 2025 6:30 PM",
      image: "https://picsum.photos/seed/acors-tr-1229/300/200",
    },
    {
      id: "#MBY-2025-1225",
      issue: "Overturned vehicle incident",
      description: "Overturned delivery van near the Sayre intersection; lane closed.",
      location: "Sayre Highway, Bangcud",
      barangay: "Bangcud",
      category: "Road Obstruction",
      status: "In Progress",
      priority: "Critical",
      reported: "June 6, 2025 7:15 AM",
      image: "https://picsum.photos/seed/acors-tr-1225/300/200",
    },
  ],
  incidents: [
    {
      id: "#MBY-2025-1241",
      title: "Stalled truck blocking Sayre lane",
      category: "Stalled Vehicles",
      barangay: "Casisang",
      status: "In Progress",
      priority: "High",
      count: 8,
      top: "52%",
      left: "55%",
    },
    {
      id: "#MBY-2025-1237",
      title: "Heavy congestion near public market",
      category: "Traffic Congestion",
      barangay: "Casisang",
      status: "Assigned",
      priority: "Medium",
      count: 10,
      top: "64%",
      left: "47%",
    },
    {
      id: "#MBY-2025-1233",
      title: "Road obstruction from fallen tree",
      category: "Road Obstruction",
      barangay: "Kalasungay",
      status: "Under Review",
      priority: "High",
      count: 6,
      top: "20%",
      left: "62%",
    },
    {
      id: "#MBY-2025-1229",
      title: "Parking violations along Rizal Avenue",
      category: "Parking Violations",
      barangay: "Sumpong",
      status: "Pending",
      priority: "Low",
      count: 4,
      top: "34%",
      left: "78%",
    },
    {
      id: "#MBY-2025-1225",
      title: "Overturned vehicle incident",
      category: "Road Obstruction",
      barangay: "Bangcud",
      status: "In Progress",
      priority: "Critical",
      count: 15,
      top: "70%",
      left: "34%",
    },
  ],
};

const healthOffice = {
  slug: "health",
  code: "DEPT-004",
  name: "City Health Office",
  shortName: "Health",
  holder: "Dr. Ana Garcia",
  email: "health@malaybalay.gov.ph",
  role: "Office Admin",
  icon: HeartPulse,
  stats: [
    { title: "Assigned to Office", value: "18", note: "+2 this week" },
    { title: "In Progress", value: "9", note: "+3 vs last week" },
    { title: "Resolved", value: "65", note: "+7 vs last week" },
    { title: "Critical", value: "2", note: "1 since yesterday" },
    { title: "Avg. Response", value: "4.2 hrs", note: "-0.5 hrs from last week" },
  ],
  categories: ["Sanitation", "Health Inspections", "Public Health", "Wellness"],
  categoryBreakdown: [
    { name: "Sanitation", percent: "38% (74)", color: "bg-red-700" },
    { name: "Health Inspections", percent: "27% (53)", color: "bg-red-600" },
    { name: "Public Health", percent: "22% (43)", color: "bg-red-500" },
    { name: "Wellness", percent: "13% (25)", color: "bg-red-400" },
  ],
  problemAreas: [
    { area: "Casisang", reports: "72 reports" },
    { area: "Sumpong", reports: "64 reports" },
    { area: "Kalasungay", reports: "58 reports" },
    { area: "Aglayan", reports: "47 reports" },
    { area: "Bangcud", reports: "39 reports" },
  ],
  priorityBreakdown: [
    { name: "Critical", count: 2, color: "bg-red-700", width: 11 },
    { name: "High", count: 7, color: "bg-red-500", width: 39 },
    { name: "Medium", count: 5, color: "bg-amber-500", width: 28 },
    { name: "Low", count: 4, color: "bg-gray-400", width: 22 },
  ],
  recentReports: [
    {
      id: "#MBY-2025-1235",
      issue: "Food safety concern at eatery",
      description: "Complaint about food handling practices at a roadside eatery.",
      location: "Public Market, Casisang",
      barangay: "Casisang",
      category: "Health Inspections",
      status: "Resolved",
      priority: "High",
      reported: "June 7, 2025 9:05 AM",
      resolved: "June 9, 2025 10:15 AM",
      image: "https://picsum.photos/seed/acors-hl-1235/300/200",
    },
    {
      id: "#MBY-2025-1224",
      issue: "Dengue watch area notice",
      description: "Barangay reporting possible dengue clustering; vector control requested.",
      location: "Purok 6, Sumpong",
      barangay: "Sumpong",
      category: "Public Health",
      status: "Assigned",
      priority: "Medium",
      reported: "June 6, 2025 2:35 PM",
      image: "https://picsum.photos/seed/acors-hl-1224/300/200",
    },
    {
      id: "#MBY-2025-1220",
      issue: "Sanitation inspection request",
      description: "Request for sanitation inspection at a communal water source.",
      location: "Purok 2, Aglayan",
      barangay: "Aglayan",
      category: "Sanitation",
      status: "Resolved",
      priority: "Medium",
      reported: "June 6, 2025 10:20 AM",
      resolved: "June 8, 2025 11:45 AM",
      image: "https://picsum.photos/seed/acors-hl-1220/300/200",
    },
    {
      id: "#MBY-2025-1216",
      issue: "Stray animal concern",
      description: "Stray dogs roaming near the school; possible health and safety risk.",
      location: "Kalasungay Central School",
      barangay: "Kalasungay",
      category: "Public Health",
      status: "In Progress",
      priority: "Low",
      reported: "June 5, 2025 4:45 PM",
      image: "https://picsum.photos/seed/acors-hl-1216/300/200",
    },
    {
      id: "#MBY-2025-1212",
      issue: "Waste disposal health hazard",
      description: "Improper waste disposal creating a breeding ground for pests.",
      location: "Purok 3, Bangcud",
      barangay: "Bangcud",
      category: "Sanitation",
      status: "Under Review",
      priority: "High",
      reported: "June 5, 2025 9:30 AM",
      image: "https://picsum.photos/seed/acors-hl-1212/300/200",
    },
  ],
  incidents: [
    {
      id: "#MBY-2025-1235",
      title: "Food safety concern at eatery",
      category: "Health Inspections",
      barangay: "Casisang",
      status: "Under Review",
      priority: "High",
      count: 9,
      top: "58%",
      left: "50%",
    },
    {
      id: "#MBY-2025-1224",
      title: "Dengue watch area notice",
      category: "Public Health",
      barangay: "Sumpong",
      status: "Assigned",
      priority: "Medium",
      count: 11,
      top: "34%",
      left: "78%",
    },
    {
      id: "#MBY-2025-1220",
      title: "Sanitation inspection request",
      category: "Sanitation",
      barangay: "Aglayan",
      status: "Pending",
      priority: "Medium",
      count: 5,
      top: "66%",
      left: "72%",
    },
    {
      id: "#MBY-2025-1216",
      title: "Stray animal concern",
      category: "Public Health",
      barangay: "Kalasungay",
      status: "In Progress",
      priority: "Low",
      count: 4,
      top: "20%",
      left: "62%",
    },
    {
      id: "#MBY-2025-1212",
      title: "Waste disposal health hazard",
      category: "Sanitation",
      barangay: "Bangcud",
      status: "Under Review",
      priority: "High",
      count: 7,
      top: "70%",
      left: "34%",
    },
  ],
};

const tourismOffice = {
  slug: "tourism",
  code: "DEPT-005",
  name: "City Tourism Office",
  shortName: "Tourism",
  holder: "Liza Fernandez",
  email: "tourism@malaybalay.gov.ph",
  role: "Office Admin",
  icon: Landmark,
  stats: [
    { title: "Assigned to Office", value: "0", note: "No routed reports" },
    { title: "In Progress", value: "0", note: "No routed reports" },
    { title: "Resolved", value: "0", note: "No routed reports" },
    { title: "Critical", value: "0", note: "No routed reports" },
    { title: "Avg. Response", value: "—", note: "Announcements only" },
  ],
  categories: ["Tourism Events", "Travel Advisories", "City Landmarks", "Promotions"],
  categoryBreakdown: [],
  problemAreas: [],
  priorityBreakdown: [],
  recentReports: [],
  incidents: [],
};

const lcroOffice = {
  slug: "lcro",
  code: "DEPT-006",
  name: "City/Municipal Civil Registrar's Office (LCRO)",
  shortName: "LCRO",
  holder: "Atty. Fernando M. Gutierrez",
  email: "lcro@malaybalay.gov.ph",
  role: "Civil Registrar",
  icon: Landmark,
  stats: [
    { title: "Total Requests", value: "42", note: "+12 this week" },
    { title: "Approved & Ready", value: "35", note: "83% auto-match" },
    { title: "Requires Review", value: "5", note: "Flagged variances" },
    { title: "In Processing", value: "2", note: "Active queue" },
    { title: "Avg. Issuance", value: "4.5 min", note: "Automated AI" },
  ],
  categories: [
    "Birth Certificate – Certified Copy",
    "Marriage Certificate – Certified Copy",
    "Death Certificate – Certified Copy",
    "Legal Instruments & Registration",
  ],
  categoryBreakdown: [
    { name: "Birth Certificate", percent: "68% (142)", color: "bg-red-700" },
    { name: "Marriage Certificate", percent: "18% (38)", color: "bg-red-500" },
    { name: "Death Certificate", percent: "10% (21)", color: "bg-red-400" },
    { name: "Legal Instruments", percent: "4% (8)", color: "bg-gray-400" },
  ],
  problemAreas: [
    { area: "Poblacion", reports: "64 requests" },
    { area: "Casisang", reports: "48 requests" },
    { area: "Sumpong", reports: "39 requests" },
    { area: "Kalasungay", reports: "28 requests" },
    { area: "Aglayan", reports: "22 requests" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 35, color: "bg-emerald-600", width: 83 },
    { name: "Under Review", count: 5, color: "bg-amber-500", width: 12 },
    { name: "Processing", count: 2, color: "bg-blue-600", width: 5 },
  ],
  recentReports: [],
  incidents: [],
};

const ctoOffice = {
  slug: "treasurer",
  code: "DEPT-008",
  name: "City Treasurer's Office",
  shortName: "Treasurer",
  holder: "Treasurer Carmela R. Villanueva",
  email: "treasurer@malaybalay.gov.ph",
  role: "City Treasurer",
  icon: Wallet,
  stats: [
    { title: "Total Requests", value: "28", note: "+8 this week" },
    { title: "Approved & Ready", value: "20", note: "71% auto-match" },
    { title: "Requires Review", value: "5", note: "Outstanding balances" },
    { title: "In Processing", value: "3", note: "Active queue" },
    { title: "Avg. Issuance", value: "3.2 min", note: "Automated AI" },
  ],
  categories: [
    "Community Tax Certificate (Cedula)",
    "Certificate of Tax Payment",
    "Certificate of Tax Clearance",
  ],
  categoryBreakdown: [
    { name: "Community Tax Certificate (Cedula)", percent: "54% (112)", color: "bg-blue-600" },
    { name: "Certificate of Tax Payment", percent: "28% (58)", color: "bg-violet-500" },
    { name: "Certificate of Tax Clearance", percent: "18% (37)", color: "bg-emerald-500" },
  ],
  problemAreas: [
    { area: "Poblacion", reports: "52 requests" },
    { area: "Casisang", reports: "41 requests" },
    { area: "Sumpong", reports: "34 requests" },
    { area: "Bangcud", reports: "22 requests" },
    { area: "Aglayan", reports: "18 requests" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 20, color: "bg-emerald-600", width: 71 },
    { name: "Under Review", count: 5, color: "bg-amber-500", width: 18 },
    { name: "Processing", count: 3, color: "bg-blue-600", width: 11 },
  ],
  recentReports: [],
  incidents: [],
};

const pdaoOffice = {
  slug: "pdao",
  code: "DEPT-009",
  name: "Persons with Disability Affairs Office",
  shortName: "PDAO",
  holder: "Officer Elena B. Corpuz",
  email: "pdao@malaybalay.gov.ph",
  role: "PDAO Head Officer",
  icon: Accessibility,
  stats: [
    { title: "Total Applications", value: "32", note: "+12 this week" },
    { title: "Approved & Issued", value: "24", note: "Registered cardholders" },
    { title: "Pending Review", value: "6", note: "Officer queue" },
    { title: "Requires Correction", value: "2", note: "Missing documents" },
    { title: "Avg. Resolution", value: "1.4 days", note: "Case verification" },
  ],
  categories: [
    "PWD Registration Certificate",
    "PWD ID",
    "Certificate of Disability",
  ],
  categoryBreakdown: [
    { name: "PWD Registration Certificate", percent: "45% (84)", color: "bg-blue-600" },
    { name: "PWD ID", percent: "38% (71)", color: "bg-emerald-500" },
    { name: "Certificate of Disability", percent: "17% (32)", color: "bg-violet-500" },
  ],
  problemAreas: [
    { area: "Sumpong", reports: "48 applicants" },
    { area: "Casisang", reports: "42 applicants" },
    { area: "Bangcud", reports: "31 applicants" },
    { area: "Poblacion", reports: "28 applicants" },
    { area: "Aglayan", reports: "20 applicants" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 24, color: "bg-emerald-600", width: 75 },
    { name: "Pending", count: 6, color: "bg-blue-600", width: 19 },
    { name: "Needs Correction", count: 2, color: "bg-amber-500", width: 6 },
  ],
  recentReports: [],
  incidents: [],
};

const cswdoOffice = {
  slug: "soloparent",
  code: "DEPT-010",
  name: "City Social Welfare & Development Office",
  shortName: "CSWDO / Solo Parent",
  holder: "Officer Carmencita P. Alvarez",
  email: "cswdo@malaybalay.gov.ph",
  role: "CSWDO Department Head",
  icon: HeartHandshake,
  stats: [
    { title: "Total Filings", value: "41", note: "+14 this week" },
    { title: "Approved & Issued", value: "30", note: "Registered solo parents" },
    { title: "Pending Review", value: "8", note: "Social worker queue" },
    { title: "Requires Correction", value: "3", note: "Missing proof" },
    { title: "Avg. Resolution", value: "1.2 days", note: "Case verification" },
  ],
  categories: [
    "Solo Parent ID",
    "Certificate of Solo Parenthood",
    "Certificate of Registration as Solo Parent",
  ],
  categoryBreakdown: [
    { name: "Solo Parent ID", percent: "52% (98)", color: "bg-emerald-600" },
    { name: "Certificate of Solo Parenthood", percent: "31% (58)", color: "bg-blue-500" },
    { name: "Certificate of Registration", percent: "17% (32)", color: "bg-violet-500" },
  ],
  problemAreas: [
    { area: "Casisang", reports: "54 applicants" },
    { area: "Sumpong", reports: "45 applicants" },
    { area: "Poblacion", reports: "39 applicants" },
    { area: "Bangcud", reports: "28 applicants" },
    { area: "Kalasungay", reports: "22 applicants" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 30, color: "bg-emerald-600", width: 73 },
    { name: "Pending", count: 8, color: "bg-blue-600", width: 20 },
    { name: "Needs Correction", count: 3, color: "bg-amber-500", width: 7 },
  ],
  recentReports: [],
  incidents: [],
};

const bploOffice = {
  slug: "bplo",
  code: "DEPT-011",
  name: "Business Permits and Licensing Office",
  shortName: "BPLO",
  holder: "Atty. Rodrigo V. Tan",
  email: "bplo@malaybalay.gov.ph",
  role: "Chief Licensing Officer",
  icon: Briefcase,
  stats: [
    { title: "Total Filings", value: "56", note: "+18 this week" },
    { title: "Approved & Issued", value: "38", note: "Active Mayor's permits" },
    { title: "Pending Review", value: "12", note: "Licensing queue" },
    { title: "Requires Correction", value: "6", note: "Clearance issues" },
    { title: "Avg. Turnaround", value: "1.6 days", note: "Online renewal" },
  ],
  categories: [
    "Business Permit Renewal",
    "Certificate of Business Closure",
    "Certificate of Business Retirement",
  ],
  categoryBreakdown: [
    { name: "Business Permit Renewal", percent: "58% (124)", color: "bg-emerald-600" },
    { name: "Certificate of Business Closure", percent: "24% (51)", color: "bg-amber-500" },
    { name: "Certificate of Business Retirement", percent: "18% (38)", color: "bg-purple-500" },
  ],
  problemAreas: [
    { area: "Poblacion", reports: "82 businesses" },
    { area: "Casisang", reports: "61 businesses" },
    { area: "Sumpong", reports: "49 businesses" },
    { area: "Aglayan", reports: "33 businesses" },
    { area: "Bangcud", reports: "25 businesses" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 38, color: "bg-emerald-600", width: 68 },
    { name: "Pending", count: 12, color: "bg-blue-600", width: 21 },
    { name: "Needs Correction", count: 6, color: "bg-amber-500", width: 11 },
  ],
  recentReports: [],
  incidents: [],
};

const oscaOffice = {
  slug: "osca",
  code: "DEPT-012",
  name: "Office for Senior Citizens Affairs",
  shortName: "OSCA",
  holder: "Mrs. Remedios L. Guingona",
  email: "osca@malaybalay.gov.ph",
  role: "OSCA Head / Senior Affairs Officer",
  icon: Users,
  stats: [
    { title: "Total Filings", value: "48", note: "+14 this week" },
    { title: "Senior IDs Issued", value: "32", note: "Active RA 9994 IDs" },
    { title: "Pending Review", value: "11", note: "Awaiting staff audit" },
    { title: "Requires Correction", value: "5", note: "Residency checks" },
    { title: "Avg. Turnaround", value: "1.2 days", note: "Free issuance" },
  ],
  categories: [
    "Senior Citizen ID",
    "Senior Citizen Registration Certificate",
    "Senior Citizen Certification",
  ],
  categoryBreakdown: [
    { name: "Senior Citizen ID", percent: "62% (112)", color: "bg-emerald-600" },
    { name: "Registration Certificate", percent: "23% (42)", color: "bg-blue-500" },
    { name: "Senior Citizen Certification", percent: "15% (27)", color: "bg-purple-500" },
  ],
  problemAreas: [
    { area: "Poblacion", reports: "68 seniors" },
    { area: "Casisang", reports: "54 seniors" },
    { area: "Sumpong", reports: "41 seniors" },
    { area: "Kalasungay", reports: "26 seniors" },
    { area: "Bangcud", reports: "21 seniors" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 32, color: "bg-emerald-600", width: 67 },
    { name: "Pending", count: 11, color: "bg-blue-600", width: 23 },
    { name: "Needs Correction", count: 5, color: "bg-amber-500", width: 10 },
  ],
  recentReports: [],
  incidents: [],
};

const assessorOffice = {
  slug: "assessor",
  code: "DEPT-013",
  name: "City Assessor's Office",
  shortName: "ASSESSOR",
  holder: "Engr. Roberto M. Dizon",
  email: "assessor@malaybalay.gov.ph",
  role: "City Assessor / Appraisal Chief",
  icon: FileText,
  stats: [
    { title: "Total Filings", value: "64", note: "+19 this week" },
    { title: "Tax Decs Issued", value: "42", note: "Certified true copies" },
    { title: "Pending Review", value: "14", note: "Cadastral mapping queue" },
    { title: "Requires Correction", value: "8", note: "Title / PIN checks" },
    { title: "Avg. Turnaround", value: "1.0 day", note: "Digital verification" },
  ],
  categories: [
    "Certified Copy of Tax Declaration",
    "Property Assessment Certification",
    "Certification of Assessed Value",
  ],
  categoryBreakdown: [
    { name: "Certified Copy of Tax Declaration", percent: "55% (138)", color: "bg-emerald-600" },
    { name: "Property Assessment Certification", percent: "28% (70)", color: "bg-blue-500" },
    { name: "Certification of Assessed Value", percent: "17% (43)", color: "bg-purple-500" },
  ],
  problemAreas: [
    { area: "Poblacion", reports: "94 parcels" },
    { area: "Casisang", reports: "72 parcels" },
    { area: "Sumpong", reports: "56 parcels" },
    { area: "Kalasungay", reports: "38 parcels" },
    { area: "Aglayan", reports: "29 parcels" },
  ],
  priorityBreakdown: [
    { name: "Approved", count: 42, color: "bg-emerald-600", width: 66 },
    { name: "Pending", count: 14, color: "bg-blue-600", width: 22 },
    { name: "Needs Correction", count: 8, color: "bg-amber-500", width: 12 },
  ],
  recentReports: [],
  incidents: [],
};

export const offices = {
  engineering: engineeringOffice,
  cenro: cenroOffice,
  cdrrmo: cdrrmoOffice,
  traffic: trafficOffice,
  health: healthOffice,
  tourism: tourismOffice,
  lcro: lcroOffice,
  treasurer: ctoOffice,
  pdao: pdaoOffice,
  soloparent: cswdoOffice,
  cswdo: cswdoOffice,
  bplo: bploOffice,
  osca: oscaOffice,
  assessor: assessorOffice,
};

export {
  engineeringOffice,
  cenroOffice,
  cdrrmoOffice,
  trafficOffice,
  healthOffice,
  tourismOffice,
  lcroOffice,
  ctoOffice,
  pdaoOffice,
  cswdoOffice,
  bploOffice,
  oscaOffice,
  assessorOffice,
};